//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public long ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string TelNumber { get; set; }
        public Nullable<byte> Channel { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public string Station { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<byte> ArchiveStateID { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<int> ArchiveUserID { get; set; }
        public string ArchiveDsc { get; set; }
        public Nullable<int> cuserid { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
    }
}
