//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM
    {
        public Nullable<short> CRMTypeID { get; set; }
        public Nullable<short> CRMStateID { get; set; }
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string Title { get; set; }
        public string Dsc { get; set; }
        public Nullable<short> CRMJobCategoryID { get; set; }
        public Nullable<int> CRMJobSubCategoryID { get; set; }
        public Nullable<int> CRMJobID { get; set; }
        public Nullable<short> CRMResultCategoryID { get; set; }
        public Nullable<int> CRMResultSubCategoryID { get; set; }
        public Nullable<int> CRMResultID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Numb { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Takh { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Dutiy { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> Bes { get; set; }
        public Nullable<double> Mandeh { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<byte> ArchiveStateID { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<int> ArchiveUserID { get; set; }
        public string ArchiveDsc { get; set; }
        public Nullable<bool> SendSMSWithTime { get; set; }
        public Nullable<System.DateTime> SendSMSWithTimeDate { get; set; }
        public string SMSWithTimeNumber { get; set; }
        public string SMSWithTimeMessage { get; set; }
        public Nullable<int> ImageID1 { get; set; }
        public Nullable<int> ImageID2 { get; set; }
        public Nullable<int> ImageID3 { get; set; }
        public Nullable<int> ImageID4 { get; set; }
        public Nullable<int> ImageID5 { get; set; }
        public Nullable<int> ImageID6 { get; set; }
        public Nullable<int> ImageID7 { get; set; }
        public Nullable<int> ImageID8 { get; set; }
        public Nullable<int> ImageID9 { get; set; }
        public Nullable<int> ImageID10 { get; set; }
        public Nullable<int> ImageID11 { get; set; }
        public Nullable<int> ImageID12 { get; set; }
        public Nullable<int> ImageID13 { get; set; }
        public Nullable<int> ImageID14 { get; set; }
        public Nullable<int> ImageID15 { get; set; }
        public Nullable<int> ImageID16 { get; set; }
        public Nullable<int> ImageID17 { get; set; }
        public Nullable<int> ImageID18 { get; set; }
        public Nullable<int> ImageID19 { get; set; }
        public Nullable<int> ImageID20 { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> RolID { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
