//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Nullable<int> CustomerGroupID { get; set; }
        public Nullable<int> CustomerSubGroupID { get; set; }
        public Nullable<short> CustomGroupID { get; set; }
        public int ID { get; set; }
        public Nullable<byte> SexTypeID { get; set; }
        public Nullable<short> JobID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Meli { get; set; }
        public Nullable<int> EmailID { get; set; }
        public Nullable<int> WebSiteID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> PhoneNumberID1 { get; set; }
        public Nullable<int> PhoneNumberID2 { get; set; }
        public Nullable<int> PhoneNumberID3 { get; set; }
        public Nullable<int> PhoneNumberID4 { get; set; }
        public string SMS { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> IdentificationID { get; set; }
        public Nullable<int> EducationID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Dsc { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<byte> Star { get; set; }
        public string RFID { get; set; }
        public Nullable<double> Mandeh { get; set; }
        public Nullable<double> ReceptionMandeh { get; set; }
        public Nullable<double> MaxBed { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> Rolid { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<int> PhoneNumberID5 { get; set; }
        public Nullable<int> PhoneNumberID6 { get; set; }
        public string BankCardNo { get; set; }
        public string BankAccNo { get; set; }
        public Nullable<bool> fav { get; set; }
    }
}
