//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public Nullable<int> NezamPezeshki { get; set; }
        public Nullable<double> Darsad { get; set; }
        public Nullable<int> TafzilID { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<byte> SexTypeID { get; set; }
        public string Meli { get; set; }
        public Nullable<int> SoldieingTypeID { get; set; }
        public string General { get; set; }
        public string Mobile { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string HomeAddress { get; set; }
        public string Dsc { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<int> limitedUserID { get; set; }
    }
}
