//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Nullable<short> Kind { get; set; }
        public Nullable<short> DocumentTypeID { get; set; }
        public Nullable<short> DocumentStateID { get; set; }
        public Nullable<short> ImagePostTypeID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> SubjectCategoryID { get; set; }
        public Nullable<int> SubjectSubCategoryID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string Title { get; set; }
        public string ShortDsc { get; set; }
        public string Dsc { get; set; }
        public byte[] DocumentFile { get; set; }
        public string FileExt { get; set; }
        public Nullable<int> ReceptionID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> ReceiverID { get; set; }
        public string SenderName { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<byte> ArchiveStateID { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<int> ArchiveUserID { get; set; }
        public string ArchiveDsc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
