//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int ID { get; set; }
        public Nullable<int> FundCategoryID { get; set; }
        public Nullable<int> FundSubCategoryID { get; set; }
        public Nullable<int> FundTypeID { get; set; }
        public Nullable<byte> SexTypeID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<short> PaymentTypeID { get; set; }
        public Nullable<int> ReceptionID { get; set; }
        public Nullable<int> ReceptionServiceID { get; set; }
        public Nullable<byte> RowID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<byte> SrcType { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> Bes { get; set; }
        public string Dsc { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<int> Rolid { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
