//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> FamilyMax { get; set; }
        public Nullable<bool> PersonalMax { get; set; }
        public Nullable<double> FamilyMaxPrice { get; set; }
        public Nullable<double> PersonalMaxPrice { get; set; }
        public string Serial { get; set; }
        public string CDName { get; set; }
        public Nullable<double> InsurancePercent { get; set; }
        public Nullable<double> PatientPercent { get; set; }
        public string Dsc { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
