//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryHeader
    {
        public int ID { get; set; }
        public Nullable<short> DayID { get; set; }
        public Nullable<short> DriverID { get; set; }
        public Nullable<short> CarID { get; set; }
        public Nullable<int> FromLocationID { get; set; }
        public Nullable<int> ToLocationID { get; set; }
        public Nullable<short> DeskID { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<byte> InOutTypeID { get; set; }
        public Nullable<byte> SaleTypeID { get; set; }
        public Nullable<short> InventoryTypeID { get; set; }
        public Nullable<short> InventoryID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerTel { get; set; }
        public string CustomerAddress { get; set; }
        public string Barnameh { get; set; }
        public Nullable<short> StorekeeperID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<double> SumNumberIn { get; set; }
        public Nullable<double> SumNumberOut { get; set; }
        public Nullable<double> SumPrices { get; set; }
        public Nullable<double> Takh { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Dutiy { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> Bes { get; set; }
        public Nullable<double> Mandeh { get; set; }
        public string Dsc { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<int> ReceptionID { get; set; }
        public Nullable<int> PatientID { get; set; }
    }
}
