//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemClass
    {
        public int ID { get; set; }
        public Nullable<short> ItemCategoryID { get; set; }
        public Nullable<int> ItemSubCategoryID { get; set; }
        public string Name { get; set; }
        public string Dsc { get; set; }
        public byte[] ICon { get; set; }
        public string IConTitle1 { get; set; }
        public string IConTitle2 { get; set; }
        public string IConTitle3 { get; set; }
        public string IConFontName { get; set; }
        public Nullable<long> IConFontColor { get; set; }
        public Nullable<int> IConFontSize { get; set; }
        public Nullable<bool> IConFontStyle { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
