//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratory
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<short> LabStateID { get; set; }
        public Nullable<int> LabCenterID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<int> FactorSerial { get; set; }
        public string SenderName { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<double> Takh { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> Bes { get; set; }
        public Nullable<double> Mandeh { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> TherapyCategoryID { get; set; }
        public Nullable<int> TherapySubCategoryID { get; set; }
        public Nullable<short> TherapyID { get; set; }
        public Nullable<int> MedicalServiceID { get; set; }
        public Nullable<double> Numb { get; set; }
        public Nullable<byte> ServiceNumb { get; set; }
        public Nullable<int> LabColorD { get; set; }
        public Nullable<short> LabServiceNumb { get; set; }
        public Nullable<int> LabJobID { get; set; }
        public Nullable<byte> UpLeft1 { get; set; }
        public Nullable<byte> UpLeft2 { get; set; }
        public Nullable<byte> UpLeft3 { get; set; }
        public Nullable<byte> UpLeft4 { get; set; }
        public Nullable<byte> UpLeft5 { get; set; }
        public Nullable<byte> UpLeft6 { get; set; }
        public Nullable<byte> UpLeft7 { get; set; }
        public Nullable<byte> UpLeft8 { get; set; }
        public Nullable<byte> UpRight1 { get; set; }
        public Nullable<byte> UpRight2 { get; set; }
        public Nullable<byte> UpRight3 { get; set; }
        public Nullable<byte> UpRight4 { get; set; }
        public Nullable<byte> UpRight5 { get; set; }
        public Nullable<byte> UpRight6 { get; set; }
        public Nullable<byte> UpRight7 { get; set; }
        public Nullable<byte> UpRight8 { get; set; }
        public Nullable<byte> DownLeft1 { get; set; }
        public Nullable<byte> DownLeft2 { get; set; }
        public Nullable<byte> DownLeft3 { get; set; }
        public Nullable<byte> DownLeft4 { get; set; }
        public Nullable<byte> DownLeft5 { get; set; }
        public Nullable<byte> DownLeft6 { get; set; }
        public Nullable<byte> DownLeft7 { get; set; }
        public Nullable<byte> DownLeft8 { get; set; }
        public Nullable<byte> DownRight1 { get; set; }
        public Nullable<byte> DownRight2 { get; set; }
        public Nullable<byte> DownRight3 { get; set; }
        public Nullable<byte> DownRight4 { get; set; }
        public Nullable<byte> DownRight5 { get; set; }
        public Nullable<byte> DownRight6 { get; set; }
        public Nullable<byte> DownRight7 { get; set; }
        public Nullable<byte> DownRight8 { get; set; }
        public Nullable<byte> UpLeftA { get; set; }
        public Nullable<byte> UpLeftB { get; set; }
        public Nullable<byte> UpLeftC { get; set; }
        public Nullable<byte> UpLeftD { get; set; }
        public Nullable<byte> UpLeftE { get; set; }
        public Nullable<byte> UpRightA { get; set; }
        public Nullable<byte> UpRightB { get; set; }
        public Nullable<byte> UpRightC { get; set; }
        public Nullable<byte> UpRightD { get; set; }
        public Nullable<byte> UpRightE { get; set; }
        public Nullable<byte> DownLeftA { get; set; }
        public Nullable<byte> DownLeftB { get; set; }
        public Nullable<byte> DownLeftC { get; set; }
        public Nullable<byte> DownLeftD { get; set; }
        public Nullable<byte> DownLeftE { get; set; }
        public Nullable<byte> DownRightA { get; set; }
        public Nullable<byte> DownRightB { get; set; }
        public Nullable<byte> DownRightC { get; set; }
        public Nullable<byte> DownRightD { get; set; }
        public Nullable<byte> DownRightE { get; set; }
        public string UpLeft1Dsc { get; set; }
        public string UpLeft2Dsc { get; set; }
        public string UpLeft3Dsc { get; set; }
        public string UpLeft4Dsc { get; set; }
        public string UpLeft5Dsc { get; set; }
        public string UpLeft6Dsc { get; set; }
        public string UpLeft7Dsc { get; set; }
        public string UpLeft8Dsc { get; set; }
        public string UpRight1Dsc { get; set; }
        public string UpRight2Dsc { get; set; }
        public string UpRight3Dsc { get; set; }
        public string UpRight4Dsc { get; set; }
        public string UpRight5Dsc { get; set; }
        public string UpRight6Dsc { get; set; }
        public string UpRight7Dsc { get; set; }
        public string UpRight8Dsc { get; set; }
        public string DownLeft1Dsc { get; set; }
        public string DownLeft2Dsc { get; set; }
        public string DownLeft3Dsc { get; set; }
        public string DownLeft4Dsc { get; set; }
        public string DownLeft5Dsc { get; set; }
        public string DownLeft6Dsc { get; set; }
        public string DownLeft7Dsc { get; set; }
        public string DownLeft8Dsc { get; set; }
        public string DownRight1Dsc { get; set; }
        public string DownRight2Dsc { get; set; }
        public string DownRight3Dsc { get; set; }
        public string DownRight4Dsc { get; set; }
        public string DownRight5Dsc { get; set; }
        public string DownRight6Dsc { get; set; }
        public string DownRight7Dsc { get; set; }
        public string DownRight8Dsc { get; set; }
        public string UpLeftADsc { get; set; }
        public string UpLeftBDsc { get; set; }
        public string UpLeftCDsc { get; set; }
        public string UpLeftDDsc { get; set; }
        public string UpLeftEDsc { get; set; }
        public string UpRightADsc { get; set; }
        public string UpRightBDsc { get; set; }
        public string UpRightCDsc { get; set; }
        public string UpRightDDsc { get; set; }
        public string UpRightEDsc { get; set; }
        public string DownLeftADsc { get; set; }
        public string DownLeftBDsc { get; set; }
        public string DownLeftCDsc { get; set; }
        public string DownLeftDDsc { get; set; }
        public string DownLeftEDsc { get; set; }
        public string DownRightADsc { get; set; }
        public string DownRightBDsc { get; set; }
        public string DownRightCDsc { get; set; }
        public string DownRightDDsc { get; set; }
        public string DownRightEDsc { get; set; }
        public byte[] Diagram { get; set; }
        public string Dsc { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<byte> ArchiveStateID { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<int> ArchiveUserID { get; set; }
        public string ArchiveDsc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
