//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalService
    {
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> BedID { get; set; }
        public Nullable<int> TherapyID { get; set; }
        public Nullable<int> ServiceCategoryID { get; set; }
        public Nullable<int> ServiceSubCategoryID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BodyID { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public Nullable<short> ServiceTime { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<double> PatientDarsad { get; set; }
        public Nullable<double> PatientPrice { get; set; }
        public Nullable<double> DoctorDarsad { get; set; }
        public Nullable<double> DoctorPrice { get; set; }
        public Nullable<double> AssistantDarsad { get; set; }
        public Nullable<double> AssistantPrice { get; set; }
        public Nullable<double> InsuranceDarsad { get; set; }
        public Nullable<double> InsurancePrice { get; set; }
        public Nullable<double> MarginPrice { get; set; }
        public Nullable<double> YaranehPrice { get; set; }
        public Nullable<double> MokamelPrice { get; set; }
        public Nullable<double> Takh { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> ZaribJ { get; set; }
        public Nullable<double> ZaribD { get; set; }
        public Nullable<double> ZaribB { get; set; }
        public Nullable<double> ZaribK { get; set; }
        public string Code { get; set; }
        public string Dsc { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> AutoSelect { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<byte> ServiceTypeID { get; set; }
    }
}
