//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BankName { get; set; }
        public Nullable<int> ChequeReceivedID { get; set; }
        public Nullable<int> ChequePaymentID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<byte> PaymentInOutTypeID { get; set; }
        public Nullable<short> PaymentTypeID { get; set; }
        public string Serial { get; set; }
        public Nullable<byte> PayerTypeID { get; set; }
        public string PayerName { get; set; }
        public string PayerMeli { get; set; }
        public string PayerAddress { get; set; }
        public string PayerBank { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> Bes { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<byte> ChequeStateID { get; set; }
        public string Dsc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> Rolid { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
