//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perm
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ValidName { get; set; }
        public string AccValid { get; set; }
        public byte[] AppValid { get; set; }
    }
}
