//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public Nullable<short> PetTypeID { get; set; }
        public Nullable<int> PetRaceID { get; set; }
        public Nullable<short> PetSexTypeID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public int ID { get; set; }
        public string PetName { get; set; }
        public string PetColor { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<short> Age { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Weight { get; set; }
        public string BCS { get; set; }
        public Nullable<bool> Aqim { get; set; }
        public string AqimDsc { get; set; }
        public Nullable<short> FoodTypeID { get; set; }
        public string Food { get; set; }
        public string FoodDsc { get; set; }
        public Nullable<bool> vaccine { get; set; }
        public string VaccineDsc { get; set; }
        public Nullable<bool> DiseaseHistory { get; set; }
        public string DiseaseHistoryDsc { get; set; }
        public Nullable<bool> FoodSensitivity { get; set; }
        public string FoodSensitivityDsc { get; set; }
        public Nullable<bool> FoodOffer { get; set; }
        public string FoodOfferDsc { get; set; }
        public Nullable<bool> SkinSensitivity { get; set; }
        public string SkinSensitivityDsc { get; set; }
        public Nullable<bool> BehaviorProblem { get; set; }
        public string BehaviorProblemDsc { get; set; }
        public string Dsc { get; set; }
        public Nullable<int> ImageID1 { get; set; }
        public Nullable<int> ImageID2 { get; set; }
        public Nullable<int> ImageID3 { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
