//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class playing
    {
        public long Id { get; set; }
        public Nullable<int> playerId { get; set; }
        public string description { get; set; }
        public System.DateTime startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public bool status { get; set; }
        public Nullable<double> price { get; set; }
        public int place { get; set; }
        public double startTimeInSecond { get; set; }
        public Nullable<double> endTimeInSecond { get; set; }
    }
}
