//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionDrug
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public Nullable<byte> RowID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<short> ItemCategoryID { get; set; }
        public Nullable<int> ItemSubCategoryID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> NumberOut { get; set; }
        public Nullable<byte> CountingUnitID { get; set; }
        public string Dsc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
