//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionGlass
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<short> GlassesTypeID { get; set; }
        public string FarRe1 { get; set; }
        public string FarRe2 { get; set; }
        public string FarReAxle { get; set; }
        public string FarReInfo { get; set; }
        public string FarLe1 { get; set; }
        public string FarLe2 { get; set; }
        public string FarLeAxle { get; set; }
        public string FarLeInfo { get; set; }
        public string FarPD { get; set; }
        public string FarPDInfo { get; set; }
        public string NearRe1 { get; set; }
        public string NearRe2 { get; set; }
        public string NearReAxle { get; set; }
        public string NearReInfo { get; set; }
        public string NearLe1 { get; set; }
        public string NearLe2 { get; set; }
        public string NearLeAxle { get; set; }
        public string NearLeInfo { get; set; }
        public string NearPD { get; set; }
        public string NearPDInfo { get; set; }
        public string Dsc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
