//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int ID { get; set; }
        public Nullable<short> PrescriptionTypeID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> ReceptionDate { get; set; }
        public Nullable<System.DateTime> FirstReceptionDate { get; set; }
        public Nullable<System.DateTime> LastReceptionDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> NextVisit { get; set; }
        public string ClinicID { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public Nullable<int> ReceptionID { get; set; }
        public Nullable<byte> RowID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<byte> SexTypeID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<int> PageNumber { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> DiagnosisID { get; set; }
        public Nullable<short> DiseaseID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> BedID { get; set; }
        public Nullable<int> TherapyCategoryID { get; set; }
        public Nullable<int> TherapySubCategoryID { get; set; }
        public Nullable<int> TherapyID { get; set; }
        public Nullable<int> TherapyCode { get; set; }
        public Nullable<int> BodyID { get; set; }
        public Nullable<int> ServiceCategoryID { get; set; }
        public Nullable<int> ServiceSubCategoryID { get; set; }
        public Nullable<int> MedicalServiceID { get; set; }
        public string ServiceCode { get; set; }
        public Nullable<short> ServiceTime { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<double> PatientPrice { get; set; }
        public Nullable<double> DoctorPrice { get; set; }
        public Nullable<double> InsurancePrice { get; set; }
        public Nullable<double> MarginPrice { get; set; }
        public Nullable<double> Takh { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> Bes { get; set; }
        public Nullable<double> Mandeh { get; set; }
        public string Dsc { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<byte> ArchiveStateID { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<int> ArchiveUserID { get; set; }
        public string ArchiveDsc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<double> Numb { get; set; }
        public Nullable<int> ReceptionServiceID { get; set; }
        public Nullable<byte> ServiceTypeID { get; set; }
        public Nullable<short> PrescriptionCashTypeID { get; set; }
    }
}
