//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionService
    {
        public Nullable<int> ReceptionID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<byte> RowID { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<double> DoctorDarsad { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<double> AssistantDarsad { get; set; }
        public Nullable<byte> SexTypeID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientMeli { get; set; }
        public string PatientGeneral { get; set; }
        public Nullable<byte> PatientAge { get; set; }
        public Nullable<double> PatientDarsad { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> DiagnosisID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> BedID { get; set; }
        public Nullable<int> BodyID { get; set; }
        public Nullable<int> BodyNumb { get; set; }
        public Nullable<int> TherapyCategoryID { get; set; }
        public Nullable<int> TherapySubCategoryID { get; set; }
        public Nullable<int> TherapyID { get; set; }
        public Nullable<int> TherapyCode { get; set; }
        public Nullable<int> ServiceCategoryID { get; set; }
        public Nullable<int> ServiceSubCategoryID { get; set; }
        public Nullable<int> MedicalServiceID { get; set; }
        public string ServiceCode { get; set; }
        public string Dsc { get; set; }
        public Nullable<double> Numb { get; set; }
        public Nullable<int> YaranehID { get; set; }
        public Nullable<int> MokamelID { get; set; }
        public Nullable<int> DiseaseID { get; set; }
        public Nullable<short> ServiceTime_P { get; set; }
        public Nullable<double> ServicePrice_P { get; set; }
        public Nullable<double> PatientPrice_P { get; set; }
        public Nullable<double> InsurancePrice_P { get; set; }
        public Nullable<double> MarginPrice_P { get; set; }
        public Nullable<double> YaranehPrice_P { get; set; }
        public Nullable<double> MokamelPrice_P { get; set; }
        public Nullable<double> DoctorPrice_P { get; set; }
        public Nullable<double> AssistantPrice_P { get; set; }
        public Nullable<double> Takh_P { get; set; }
        public Nullable<double> Bed_P { get; set; }
        public Nullable<double> ZaribJ_P { get; set; }
        public Nullable<double> ZaribD_P { get; set; }
        public Nullable<double> ZaribB_P { get; set; }
        public Nullable<double> ZaribK_P { get; set; }
        public Nullable<short> ServiceTime { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<bool> SetItemsPrice { get; set; }
        public Nullable<int> InventoryHeaderID { get; set; }
        public Nullable<double> ItemsPrice { get; set; }
        public Nullable<double> PatientPrice { get; set; }
        public Nullable<double> InsurancePrice { get; set; }
        public Nullable<double> MarginPrice { get; set; }
        public Nullable<double> YaranehPrice { get; set; }
        public Nullable<double> MokamelPrice { get; set; }
        public Nullable<double> DoctorPrice { get; set; }
        public Nullable<double> AssistantPrice { get; set; }
        public Nullable<double> Takh { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> Bes { get; set; }
        public Nullable<double> Mandeh { get; set; }
        public Nullable<double> ZaribJ { get; set; }
        public Nullable<double> ZaribD { get; set; }
        public Nullable<double> ZaribB { get; set; }
        public Nullable<double> ZaribK { get; set; }
        public Nullable<byte> UpLeft1 { get; set; }
        public Nullable<byte> UpLeft2 { get; set; }
        public Nullable<byte> UpLeft3 { get; set; }
        public Nullable<byte> UpLeft4 { get; set; }
        public Nullable<byte> UpLeft5 { get; set; }
        public Nullable<byte> UpLeft6 { get; set; }
        public Nullable<byte> UpLeft7 { get; set; }
        public Nullable<byte> UpLeft8 { get; set; }
        public Nullable<byte> UpRight1 { get; set; }
        public Nullable<byte> UpRight2 { get; set; }
        public Nullable<byte> UpRight3 { get; set; }
        public Nullable<byte> UpRight4 { get; set; }
        public Nullable<byte> UpRight5 { get; set; }
        public Nullable<byte> UpRight6 { get; set; }
        public Nullable<byte> UpRight7 { get; set; }
        public Nullable<byte> UpRight8 { get; set; }
        public Nullable<byte> DownLeft1 { get; set; }
        public Nullable<byte> DownLeft2 { get; set; }
        public Nullable<byte> DownLeft3 { get; set; }
        public Nullable<byte> DownLeft4 { get; set; }
        public Nullable<byte> DownLeft5 { get; set; }
        public Nullable<byte> DownLeft6 { get; set; }
        public Nullable<byte> DownLeft7 { get; set; }
        public Nullable<byte> DownLeft8 { get; set; }
        public Nullable<byte> DownRight1 { get; set; }
        public Nullable<byte> DownRight2 { get; set; }
        public Nullable<byte> DownRight3 { get; set; }
        public Nullable<byte> DownRight4 { get; set; }
        public Nullable<byte> DownRight5 { get; set; }
        public Nullable<byte> DownRight6 { get; set; }
        public Nullable<byte> DownRight7 { get; set; }
        public Nullable<byte> DownRight8 { get; set; }
        public Nullable<byte> UpLeftA { get; set; }
        public Nullable<byte> UpLeftB { get; set; }
        public Nullable<byte> UpLeftC { get; set; }
        public Nullable<byte> UpLeftD { get; set; }
        public Nullable<byte> UpLeftE { get; set; }
        public Nullable<byte> UpRightA { get; set; }
        public Nullable<byte> UpRightB { get; set; }
        public Nullable<byte> UpRightC { get; set; }
        public Nullable<byte> UpRightD { get; set; }
        public Nullable<byte> UpRightE { get; set; }
        public Nullable<byte> DownLeftA { get; set; }
        public Nullable<byte> DownLeftB { get; set; }
        public Nullable<byte> DownLeftC { get; set; }
        public Nullable<byte> DownLeftD { get; set; }
        public Nullable<byte> DownLeftE { get; set; }
        public Nullable<byte> DownRightA { get; set; }
        public Nullable<byte> DownRightB { get; set; }
        public Nullable<byte> DownRightC { get; set; }
        public Nullable<byte> DownRightD { get; set; }
        public Nullable<byte> DownRightE { get; set; }
        public byte[] Diagram { get; set; }
        public Nullable<byte> DentalKindID { get; set; }
        public Nullable<short> DentalStateID { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> CancelUserID { get; set; }
        public string CancelDsc { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public Nullable<int> LaboratoryID { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> RolID { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<int> CentralID { get; set; }
        public Nullable<byte> ServiceTypeID { get; set; }
        public Nullable<int> PetID { get; set; }
    }
}
