//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> WorkCalendarID { get; set; }
        public Nullable<short> DayID { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<double> DoctorDarsad { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<double> AssistantDarsad { get; set; }
        public Nullable<byte> SexTypeID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientMeli { get; set; }
        public string PatientGeneral { get; set; }
        public Nullable<byte> PatientAge { get; set; }
        public Nullable<double> PatientDarsad { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> DiagnosisID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> BedID { get; set; }
        public Nullable<int> BodyID { get; set; }
        public Nullable<short> BodyNumb { get; set; }
        public Nullable<short> SumBodyNumb { get; set; }
        public Nullable<short> BodyCount { get; set; }
        public Nullable<int> DentalInformationID { get; set; }
        public Nullable<int> TherapyCategoryID { get; set; }
        public Nullable<int> TherapySubCategoryID { get; set; }
        public Nullable<int> TherapyID { get; set; }
        public Nullable<int> TherapyCode { get; set; }
        public Nullable<int> ServiceCategoryID { get; set; }
        public Nullable<int> ServiceSubCategoryID { get; set; }
        public Nullable<int> MedicalServiceID { get; set; }
        public string ServiceCode { get; set; }
        public string MedicalServiceDsc { get; set; }
        public Nullable<double> Numb { get; set; }
        public Nullable<double> ServiceTime { get; set; }
        public Nullable<short> ServiceCount { get; set; }
        public Nullable<double> SumNumb { get; set; }
        public Nullable<short> VisitCount { get; set; }
        public Nullable<double> SumServiceTime { get; set; }
        public Nullable<int> YaranehID { get; set; }
        public Nullable<int> MokamelID { get; set; }
        public Nullable<int> DiseaseID { get; set; }
        public Nullable<bool> SetItemsPrice { get; set; }
        public Nullable<int> InventoryHeaderID { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<double> ItemsPrice { get; set; }
        public Nullable<double> PatientPrice { get; set; }
        public Nullable<double> InsurancePrice { get; set; }
        public Nullable<double> MarginPrice { get; set; }
        public Nullable<double> YaranehPrice { get; set; }
        public Nullable<double> MokamelPrice { get; set; }
        public Nullable<double> DoctorPrice { get; set; }
        public Nullable<double> AssistantPrice { get; set; }
        public Nullable<double> Takh { get; set; }
        public Nullable<double> Bed { get; set; }
        public Nullable<double> Bes { get; set; }
        public Nullable<double> Mandeh { get; set; }
        public Nullable<double> ZaribJ { get; set; }
        public Nullable<double> ZaribD { get; set; }
        public Nullable<double> ZaribB { get; set; }
        public Nullable<double> ZaribK { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public Nullable<int> LaboratoryID { get; set; }
        public Nullable<short> ReceptionTypeID { get; set; }
        public Nullable<short> ReceptionStateID { get; set; }
        public Nullable<short> PaymentStateID { get; set; }
        public Nullable<short> PaymentTypeID { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<byte> ArchiveStateID { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<int> ArchiveUserID { get; set; }
        public string ArchiveDsc { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> CancelUserID { get; set; }
        public string CancelDsc { get; set; }
        public string ShortDsc { get; set; }
        public string Dsc { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> CentralID { get; set; }
        public Nullable<int> RolID { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<byte> ServiceTypeID { get; set; }
        public Nullable<byte> ReceptionUI { get; set; }
        public Nullable<int> PetID { get; set; }
    }
}
