//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionImage
    {
        public int ID { get; set; }
        public Nullable<byte> ImageKindID { get; set; }
        public Nullable<short> ImageTypeID { get; set; }
        public Nullable<short> ArchiveTypeID { get; set; }
        public Nullable<int> ReceptionID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string ImageTitle { get; set; }
        public byte[] imageFile { get; set; }
        public string Dsc { get; set; }
        public Nullable<System.DateTime> write_date { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
