//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanadType
    {
        public Nullable<int> SanadCategoryID { get; set; }
        public Nullable<int> SanadSubCategoryID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<byte> Kind { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Dsc { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
