//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSBank
    {
        public int ID { get; set; }
        public Nullable<int> SMSDeviceID { get; set; }
        public Nullable<short> MessageKindID { get; set; }
        public Nullable<int> SMSID { get; set; }
        public Nullable<short> SMSStateID { get; set; }
        public string SenderNumber { get; set; }
        public string SenderName { get; set; }
        public string SMSNumber { get; set; }
        public string SMSMessage { get; set; }
        public Nullable<byte> MessageNumb { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> SentStateID { get; set; }
        public Nullable<short> SentTypeID { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsReply { get; set; }
        public Nullable<int> MessageTypeID { get; set; }
        public Nullable<byte> ServerSendingMode { get; set; }
        public Nullable<int> StationID { get; set; }
        public string ComputerName { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> SrcType { get; set; }
        public Nullable<int> SrcID { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
