//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapyItem
    {
        public int ID { get; set; }
        public Nullable<short> RowID { get; set; }
        public Nullable<int> TherapyID { get; set; }
        public Nullable<bool> AutoSelect { get; set; }
        public Nullable<short> ItemCategoryID { get; set; }
        public Nullable<int> ItemSubCategoryID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<byte> CountingUnitID { get; set; }
        public Nullable<double> NumberOut { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Takh { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Dutiy { get; set; }
        public string Dsc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
