//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran
    {
        public int id { get; set; }
        public System.DateTime trdate { get; set; }
        public int userid { get; set; }
        public Nullable<short> stationid { get; set; }
        public Nullable<byte> actid { get; set; }
        public Nullable<int> objectid { get; set; }
        public Nullable<int> rowid { get; set; }
    }
}
