//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public Nullable<int> rolid { get; set; }
        public byte usertypeid { get; set; }
        public int id { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string username { get; set; }
        public string loginname { get; set; }
        public byte[] pwd { get; set; }
        public string dsc { get; set; }
        public string accvalid { get; set; }
        public byte[] AppValid { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> ImageID { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
    }
}
