//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHall.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCalendar
    {
        public int ID { get; set; }
        public Nullable<byte> SexTypeID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<short> InsuranceID { get; set; }
        public Nullable<int> DiseaseID { get; set; }
        public Nullable<short> DepartmentID { get; set; }
        public Nullable<int> TherapyID { get; set; }
        public Nullable<int> MedicalServiceID { get; set; }
        public Nullable<double> Numb { get; set; }
        public Nullable<System.DateTime> AppointmentTime { get; set; }
        public Nullable<short> AppointmentRate { get; set; }
        public Nullable<bool> Delay { get; set; }
        public string ComeTime { get; set; }
        public Nullable<bool> NotCome { get; set; }
        public Nullable<bool> Done { get; set; }
        public string Dsc { get; set; }
        public Nullable<short> WorkCalendarStateID { get; set; }
        public Nullable<double> Bes { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<int> NoteID1 { get; set; }
        public Nullable<int> NoteID2 { get; set; }
        public Nullable<int> NoteID3 { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<System.DateTime> BesRegisterDate { get; set; }
    }
}
